### ISSUE TITLE
Tasklist alignment issue

### ISSUE THREAD

**Issue by facelessuser** [sindresorhus/github-markdown-css#10]
Didn't notice this at first because I was using a straight up tasklist for testing, but after awhile I noticed it was indented too far.  This is much more noticeable when you mix list types.

``` markdown
- item 1
    - [X] item A
    - [X] item B
        1. item a
```

The reason is because the Github Markdown API is not consistent with what actually get used on a github repo or in the comment section.

The CSS is looking for the input item to have a class of `task-list-item-checkbox`:

``` css
.markdown-body .task-list-item-checkbox {
  margin: 0 4px 0.25em -20px;
  vertical-align: middle;
}
```

But the the API returns all the tasklist items without this class (I don't understand why they don't use the **exact** same API internally and externally via the API, but they seem to not).

Something like this should be good enough.

``` css
.markdown-body .task-list-item input {
  margin: 0 4px 0.25em -20px;
  vertical-align: middle;
}
```

I will take a look at these within the next week if no one else does.  But I wanted to document the issue.
