### ISSUE TITLE
GitHub dark isn't coloring table text correctly

### ISSUE THREAD

**Issue by Sombody101** [sindresorhus/github-markdown-css#109]
Tables using the dark CSS file all have dark text color
![image](https://github.com/sindresorhus/github-markdown-css/assets/84810042/66f60c83-b68f-4c95-a52f-c2466ac8715b)

I don't want to go into the CSS because I don't trust that I can fix it myself so that it won't interfere with other styles applied to each cell.

**Comment by supporttxend** [comment]
**ss**

**Comment by slydor** [comment]
Hi! I had the same issue with Brave in Ubuntu with default dark theme. I looked into the applied styles and found out, the browser applied some styles on the table element (called 'user agent stylesheet'):

```css
table {
    border-collapse: separate;
    text-indent: initial;
    line-height: normal;
    font-weight: normal;
    font-size: medium;
    font-style: normal;
    color: -internal-quirk-inherit; /* <--- this one overrides the correct font color */
    text-align: start;
    border-spacing: 2px;
    white-space: normal;
    font-variant: normal;
}
```
According to https://stackoverflow.com/questions/24258380/font-color-in-a-table-doesnt-inherit-from-parent-div I needed to simply specify a doctype. I added this to the top of my html file and the browser stopped running in 'Quirks' mode:
```html
<!DOCTYPE html>
```
Maybe that's your issue as well.
