### ISSUE TITLE
`.markdown-body .octicon` css style out of sync with GitHub

### ISSUE THREAD

**Issue by tylerlong** [sindresorhus/github-markdown-css#20]
GitHub:

![screen shot 2016-01-08 at 11 44 49 pm](https://cloud.githubusercontent.com/assets/733544/12201924/e2f2edce-b661-11e5-907d-b901d8492398.png)

This project:

```css
.markdown-body .octicon {
  font: normal normal normal 16px/1 octicons-anchor;
  display: inline-block;
  text-decoration: none;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

Difference is `octicons` vs `octicons-anchor`.
