### ISSUE TITLE
Fix anchor link style missing

### ISSUE THREAD

**Issue by tylerlong** [sindresorhus/github-markdown-css#29]
For some reason the following doesn't work any more:

``` css
.markdown-body h1:hover .anchor .octicon-link,
.markdown-body h2:hover .anchor .octicon-link,
.markdown-body h3:hover .anchor .octicon-link,
.markdown-body h4:hover .anchor .octicon-link,
.markdown-body h5:hover .anchor .octicon-link,
.markdown-body h6:hover .anchor .octicon-link {
  visibility: visible;
}
```

It is reproducable in the [demo page](https://sindresorhus.com/github-markdown-css/).
