### ISSUE TITLE
max-width : auto is invalid

### ISSUE THREAD

**Issue by hezedu** [sindresorhus/github-markdown-css#31]
```css
.markdown-body pre code {
    display: inline;
    max-width: auto;
    padding: 0;
    margin: 0;
    overflow: visible;
    line-height: inherit;
    word-wrap: normal;
    background-color: transparent;
    border: 0;
}
```
