### ISSUE TITLE
Header anchor on hover

### ISSUE THREAD

**Issue by simov** [sindresorhus/github-markdown-css#6]
:wave: 

I just used the GitHub's API to render some markdown and it puts

``` html
<h1>
    <a name="anchor-name" class="anchor" href="#anchor-name" aria-hidden="true">
    <span class="octicon octicon-link"></span></a>
    Header
</h1>
```

So just for the record I needed to copy these additional styles from GitHub to get the same feel as on the GitHub's readme files

``` css
@font-face {
    font-family: 'octicons';
    src: url('../octicons/octicons.eot?#iefix') format('embedded-opentype'),
        url('../octicons/octicons.woff') format('woff'),
        url('../octicons/octicons.ttf') format('truetype'),
        url('../octicons/octicons.svg#octicons') format('svg');
    font-weight: normal;
    font-style: normal;
}

.octicon {
    font: normal normal 16px octicons;
    line-height: 1;
    display: inline-block;
    text-decoration: none;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
.octicon-link:before { content: '\f05c'; }

.markdown-body .octicon-link {
    display: none;
    color: #000;
    vertical-align: middle;
}
.markdown-body h1:hover .anchor,
.markdown-body h2:hover .anchor,
.markdown-body h3:hover .anchor,
.markdown-body h4:hover .anchor,
.markdown-body h5:hover .anchor,
.markdown-body h6:hover .anchor {
    height: 1em;
    padding-left: 8px;
    margin-left: -30px;
    line-height: 1;
    text-decoration: none;
}
.markdown-body h1:hover .octicon-link,
.markdown-body h2:hover .octicon-link,
.markdown-body h3:hover .octicon-link,
.markdown-body h4:hover .octicon-link,
.markdown-body h5:hover .octicon-link,
.markdown-body h6:hover .octicon-link {
    display: inline-block;
}
```
