### ISSUE TITLE
Tiny text in recent commit

### ISSUE THREAD

**Issue by facelessuser** [sindresorhus/github-markdown-css#8]
Normally the default text size in github markdown is 16px.  Recent changes define text as 16px, but then override the default text with this to 13px:

``` css
.markdown-body,
.markdown-body input {
  font: 13px Helvetica, arial, freesans, clean, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol";
  line-height: 1.4;
}
```

As `.markdown-body` has already had its font and font size defined early on, I feel this should be:

``` css
.markdown-body input {
  font: 13px Helvetica, arial, freesans, clean, sans-serif, "Segoe UI Emoji", "Segoe UI Symbol";
  line-height: 1.4;
}
```
