### ISSUE TITLE
does --color-fg-default apply on text color?

### ISSUE THREAD

**Issue by Hunkoys** [sindresorhus/github-markdown-css#90]
I used this css on another extension and I notice the text in dark mode didn't quite match github's. So I made another rule to fix that
`.markdown-preview * {  color: var(--color-fg-default); }` 

Not sure if it was just me.

**Comment by hyrious** [comment]
This rule does exist, I think there may be some other rule's specificity higher than it?
```css
.markdown-body {
  color: var(--color-fg-default);
}
```
